### ISSUE TITLE
Abhänigkeiten in observer.py

### ISSUE THREAD

**Issue by vKleistk** [seiferta/eMonitor#13]
Hallo,

>Traceback (most recent call last):
> File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 108, in run_job
>    retval = job.func(*job.args, **job.kwargs)
>  File "/home/kevin/Schreibtisch/emonitor/emonitor/observer.py", line 30, in observeFolder
>    if not os.path.exists(path):
>  File "/usr/lib/python2.7/genericpath.py", line 18, in exists
>    os.stat(path)
>TypeError: coercing to Unicode: need string or buffer, NoneType found

Folgende Fehlermeldung erhalte ich bei einem Start von eMonitor.

Angaben zur Umgebung:
Gastsystem: Ubuntu 12.04 via VirtualBox
Folgende Schritte habe ich ausgeführt:
installation python, apt-get upgrade, pip -r req... .txt, python main.py -p 80 -t

Ich bin mir nicht ganz sicher ob es sich hierbei um einen Bedienerfehler handelt, wenn ja, lasse ich mich gerne aufklären, a

Um Hilfe wäre ich dankbar.
Kameradschaftlichen Gruß
Kevin von Kleist

**Comment by seiferta** [comment]
Hallo,
es scheint daran zu liegen, dass kein Pfad angegeben wurde, der überwacht werden soll. Liegt im Basispfad von eMonitor die Datei emonitor.cfg (Kopie von emonitor.cfg.template) mit den angepassten Pfaden? Habe gerade gesehen, dass das in der Anleitung im Wiki noch gefehlt hatte.

**Comment by vKleistk** [comment]
Okay, fühlt sich jetzt ganz gut an, was das Terminal da zu mir spricht.

>INFO:eMonitor:scheduler: job added "observer"
>INFO:eMonitor:modules: 15 modules loaded

Danke, aber eine Frage habe ich jetzt noch, ist das ganze jetzt als Dienst im Hintergrund aktiv? Wie bekomme ich den Prozess zum standby? und wie komme ich auf die Konfigurationsoberfläche? 

PS. Wenn du nichts da gegen hast, würde ich das Wiki dann mit meinen Erfahrungen füttern wollen?

**Comment by seiferta** [comment]
gut, dass das klappt.
Bin noch nicht dazu gekommen, das Wiki mit allen Infos und Doku zu füttern. Wenn Fragen sind, kannst du gerne Inhalte produzieren. Ich will versuchen, das möglichst schnell zu Supporten.

- Unter Linux sollte der Aufruf einfach mit python main.py & in den Hintergrund geschoben werden können. Unter Windows klappt das mit pythonw.exe main.py

- Die Konfigurationsoberfläche ist über den Browser zu erreichen http://localhost:[port]/admin
Benutzername/Passwort: Administrator/admin (kann im AdminBereich geändert werden)
