### ISSUE TITLE
Modul Straßenkarte - Download Fehlender Zoom

### ISSUE THREAD

**Issue by vKleistk** [seiferta/eMonitor#15]
Im Downloadmanager von OpenStreetMap fehlen die Zoombuttons, für eine schnellere Navigation

**Comment by seiferta** [comment]
Der Zoom ist absichtlich nicht vorhanden. Man braucht ihn eigentlich auch nicht, wenn man unter **/admin/maps/position** die Startposition der Karte definiert. Das geht über eine Suche nach dem Ort innerhalb von OpenStreetMap.
Anschließend steht der Downloadmanager bereits auf der korrekten Stelle, zu der man die Kartenteile laden möchte.
