### ISSUE TITLE
Scrollleisten

### ISSUE THREAD

**Issue by vKleistk** [seiferta/eMonitor#18]
Die Scrolleisten im Broweser werden nicht korrekt angezeigt. 
Scrollen mit Mausrad nicht möglich./ Scrolleiste nicht vorhanden
Jedoch mit makieren des Textes.

Mac OSX 10.1 / Safari 8.0

**Comment by seiferta** [comment]
An welcher Stelle ist das aufgefallen?
Mit Safari 5 unter Windows ist das nicht nachvollziehbar, da sind die Scrollbars vorhanden.

**Comment by vKleistk** [comment]
Ich zweifele grade an mir selbst.

Anscheinend tritt der Fehler sporadisch auf?

Kann ihn heute nicht mehr reproduzieren mit neuem Nightliy.

#closed
