### ISSUE TITLE
Fehler beim Laden der Hausnummern aus OSM

### ISSUE THREAD

**Issue by sambandi** [seiferta/eMonitor#24]
Nach dem Anlegen eines Orts werden alle Straßen des Orts geladen. Allerdings können die Hausnummern der einzelnen Straßen nicht geladen werden. 

Im eMonitor-error.log habe ich folgenden Eintrag gefunden:
2015-09-04 07:49:29,884 - ERROR - cherrypy.error - [04/Sep/2015:07:49:29] ENGINE ValueError('could not convert string to float: ',)

Als Beispiel dient diese OSM Straße: http://www.openstreetmap.org/way/74863178

**Comment by seiferta** [comment]
habe besehen, dass im beschriebenen Fall die Straße nicht innerhalb einer normalen Ortsgrenze liegt. Das ist ein Sonderfall, der bisher nicht aufgetreten ist und genauer untersucht werden muss

**Comment by sambandi** [comment]
Ich habe diese Problematik nun genauer untersucht und rausgefunden, dass ich damals die Hausnummern als Annotation/Addresses in diesen Ortsteil eingetragen habe. Solche Informationen werden in der Suchanfrage nach Hausnummern im Skript noch nicht berücksichtigt. Zum Testen haben wir in der anliegenden Straße (Rosenweg) Gebäude eingezeichnet und das Einlesen der Hausnummern klappte sofort problemlos.
