### ISSUE TITLE
eMonitor is not loading the webfrontend

### ISSUE THREAD

**Issue by moritzklein** [seiferta/eMonitor#40]
Installed eMonitor on:
- Windows 10
- python 2.7, and all the stuff written in the manual...

When starting eMonitor:
```
C:\eMonitorSrv>python run.py
DEBUG:emonitor.signals:add signal monitorserver.clientsearchstart
DEBUG:emonitor.signals:add signal monitorserver.clientsearchdone
DEBUG:emonitor.signals:add signal monitorserver.clientanswer
ERROR:emonitor.communication:error telegram
INFO:emonitor.communication:2 Communicator(s) loaded: telegram, mail
```
Nothing more...
Webinterface is not loading, firewall is off.
eMonitor-error.log does not say more than the error msg show above.

What else could I do?

**Comment by seiferta** [comment]
please update sources and update required python modules (requirements.txt)

for telegram support read http://seiferta.github.io/eMonitor/details/ and install python-telegram-bot module

**Comment by moritzklein** [comment]
sources are up to date and  python modules (requirements.txt) are up to date.
the python-telegram-bot was the missing part. thx! so the python-telegram-bot is a required part for execution!

**Comment by seiferta** [comment]
after code changes/fixes python-telegram-bot module is optional. only needed if telegam connection configured and used.
