### ISSUE TITLE
Fehlermeldung von Alembic beim Start von eMonitor

### ISSUE THREAD

**Issue by clfromhell** [seiferta/eMonitor#51]
Seit dem neuesten Update lässt sich eMonitor nicht mehr starten und bringt folgenden Trace:

@AlarmServer ~ # Traceback (most recent call last):               :(   File "./run.py", line 5, in <module>
    from emonitor import app
  File "/root/eMonitor/emonitor/**init**.py", line 8, in <module>
    app = create_app()
  File "/root/eMonitor/emonitor/app.py", line 82, in create_app
    configure_extensions(app)
  File "/root/eMonitor/emonitor/app.py", line 131, in configure_extensions
    if alembic.migration_context.get_current_heads()[0] != current_app.config.get('DB_VERSION'):  # update version
AttributeError: 'Alembic' object has no attribute 'migration_context'

Liegt das Problem evtl. an der Version von Alembic aus der "requirements.txt"? Mit der neuesten Version von Alembic bekomme ich jedoch den eMonitor auch nicht mehr zum Laufen.

**Comment by seiferta** [comment]
Mit Version 0.8.8 von alembic funktioniert der Start wieder.
Habe gerade die requirements.txt entsprechend aktualisiert. Es haben sich auch noch ein paar andere Module aktualisiert, bitte testen.

**Comment by clfromhell** [comment]
Bekomme den eMonitor auch mit den aktualisierten requirements nicht zum Laufen, es kommt nun ein anderer Trace:

@AlarmServer ~ # /usr/local/lib/python2.7/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  .format(x=modname), ExtDeprecationWarning
/usr/local/lib/python2.7/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy._compat is deprecated, use flask_sqlalchemy._compat instead.
  .format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
  File "./run.py", line 5, in <module>
    from emonitor import app
  File "/root/eMonitor/emonitor/__init__.py", line 7, in <module>
    from app import create_app
  File "/root/eMonitor/emonitor/app.py", line 7, in <module>
    from .extensions import alembic, db, login_manager, babel, cache, events, scheduler, monitorserver, signal, printers, communication
  File "/root/eMonitor/emonitor/extensions.py", line 17, in <module>
    from flask_alembic import Alembic
  File "/usr/local/lib/python2.7/dist-packages/flask_alembic/__init__.py", line 13, in <module>
    from flask_alembic.extension import Alembic
  File "/usr/local/lib/python2.7/dist-packages/flask_alembic/extension.py", line 8, in <module>
    from alembic.revision import ResolutionError
ImportError: No module named revision

**Comment by seiferta** [comment]
habe nochmal eine neue Umgebung für Tests aufgesetzt und ein paar kleine Änderungen eingebaut. Anscheinend hatten zwei logger-Einträge Probleme beim Starten verursacht.
commit folgt

**Comment by clfromhell** [comment]
Nach dem Update startet eMonitor wieder wie gewohnt, jedoch bekomme ich seitdem einen Error 500 beim Öffnen der Grundeinstellungen. Anbei ein weiterer Trace:

emonitor/admin/web/templates/admin.html", line 52, in top-level template code
    <div style="padding:20px;">{%- block content %}{% endblock -%}</div>
  File "/root/eMonitor/emonitor/modules/settings/templates/admin.settings.html", line 71, in block "content"
    <p>{{ _('settings.db.currentrevision') }}: <span id="dbstate">{{ alembic.context.get_current_revision() }}</span></p>
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 408, in getattr
    return getattr(obj, attribute)
UndefinedError: 'flask_alembic.extension.Alembic object' has no attribute 'context'.
