### ISSUE TITLE
Fehler beim Starten von eMonitor: IndexError: tuple index out of range

### ISSUE THREAD

**Issue by emonitorfeuerwehrdegerndorf** [seiferta/eMonitor#52]
Servus zusammen.
Wir bekommen beim Start von eMonitor folgende Fehlermeldung.

Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from emonitor import app
  File "C:\emonitor\emonitor\__init__.py", line 8, in <module>
    app = create_app()
  File "C:\emonitor\emonitor\app.py", line 82, in create_app
    configure_extensions(app)
  File "C:\emonitor\emonitor\app.py", line 131, in configure_extensions
    if alembic.migration_context.get_current_heads()[0] != current_app.config.ge
t('DB_VERSION'):  # update version
IndexError: tuple index out of range

Wir bitte um Hilfe wie wir den Fehler beseitigen können.
Python Pakete wurden alle mit pip install --upgrade aktualisiert.
eMonitor Version ist die 0.5.0-29-g5a1f8ab

**Comment by seiferta** [comment]
Das Problem liegt am Python Paket _alembic_
Unter welchem OS soll eMonitor laufen? Wird Python in 32-Bit oder 64-Bit eingesetzt? Welche Versionen der Python Pakete sind aktuell installiert (_pip freeze_)

Sonst können kurzfristig in der Datei _emonitor/app.py_ die Zeilen _131-135_ auskommentiert werden, dann startet der Server wieder.

**Comment by emonitorfeuerwehrdegerndorf** [comment]
OS ist Windows 7 Pro 64-Bit
Python wird als 32-Bit eingesetzt

[Versionen.txt](https://github.com/seiferta/eMonitor/files/601065/Versionen.txt)
