### ISSUE TITLE
Evaluierungsproblem einer Straße, die in mehreren Orten existiert 

### ISSUE THREAD

**Issue by sambandi** [seiferta/eMonitor#54]
In unserer Umgebung existiert z.B.: die Hauptstraße 22 in drei angrenzenden Ortschaften. Die Ortschaften und dessen Straßen sind im Emonitor hinterlegt. Bei der Evaluierung  der Straße beim Eingang eines Einsatzes über den generischen Faxchecker wird stets der erste Match in der Datenbank zurückgegeben.

Auch ein vorheriges evaluieren der Ortschaft bewirkt keine Änderung, da die Evaluierungsmethode für die Straße die Ortschaft nicht berücksichtigt.

**Comment by seiferta** [comment]
Das stimmt, der Fall wird bisher nicht berücksichtigt.
