### ISSUE TITLE
Fehler bei der requirements.txt installation

### ISSUE THREAD

**Issue by 12Markus34** [seiferta/eMonitor#61]
Hallo,

akteull schaffe ich es nicht die Befehlszeile pip install -r requirements.txt erfolgreich auszuführen.

Bei mir wird die Installation wie folgt abgebrochen (wenn ich es richtig gelesen aheb, müsste das ein Problem mit Pillow 3.4.2 sein):

ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting
___________________________________
Can't roll back Pillow; was not uninstalled
Cleaning up...
(...)
Sollte mehr Fehlertext von Nöten sein, tippe ich ihn gerne weiter ab ;)

Viele Grüße und im voraus besten Dank!

**Comment by seiferta** [comment]
Kann mir das nur erklären, dass unter Linux nicht die notwendigen jpeg-Libs installiert waren. Dann kann es zu Problemen mit Pillow kommen.
Das ist allerdings bei jeder Distribution etwa anders.
