### ISSUE TITLE
VirtualBox Image - Testverarbeitung Alarmfax - Parameter 'out.fields'nicht gefunden

### ISSUE THREAD

**Issue by feller1002** [seiferta/eMonitor#69]
Hallo zusammen!

Ich habe gerade das VirtualBox Image getestet. Wenn ich eine Testverarbeitung eines Alarmfaxes durchführen möchte, bekomme ich die Fehlermeldung "Parameter 'out.fields'nicht gefunden".

Mittlerweile habe ich herausgefunden, dass es hier wohl Probleme bei dem Eventhandler gibt. Leider bin ich in der Doku nicht fündig geworden, wie ich diesen Fehler beheben kann, bzw. welche Einstellungen im Eventhandler ich durchführen muss.
Wie kann ich diesen Fehler beheben?

Wenn ich das System nicht nur Testweise einsetzen möchte, ist hier das VirtualBox Image ausreichend, oder ist eine komplette Installation sinnvoller?

Vielen Dank!

**Comment by seiferta** [comment]
mit was für einem Fax ist denn der Test gemacht worden?

**Comment by feller1002** [comment]
Mit einem Standard-Fax von unserer Leitstelle (ILS Bayerischer Untermain)

**Comment by seiferta** [comment]
Damit kann es auch nicht funktionieren, bevor nicht die Faxdefinition an das Layout der Leitstelle Untermain angepasst ist.
Leider nutzt jede ILS in Bayern ein etwas anderes Layout, somit geht das nicht ohne Anpassungen.
