### ISSUE TITLE
flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead

### ISSUE THREAD

**Issue by jonny1213** [seiferta/eMonitor#71]
Hallo,
bekomme beim starten (pyhton run.py) folgendes:
python run.py
/usr/local/lib/python2.7/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  .format(x=modname), ExtDeprecationWarning
/usr/local/lib/python2.7/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy._compat is deprecated, use flask_sqlalchemy._compat instead.
  .format(x=modname), ExtDeprecationWarning
no config file found, using DEFAULT_CONFIG
/usr/local/lib/python2.7/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.cache is deprecated, use flask_cache instead.
  .format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
  File "run.py", line 41, in <module>
    main()
  File "run.py", line 31, in main
    from emonitor import app
  File "/root/eMonitor/emonitor/__init__.py", line 9, in <module>
    app = create_app(args.get('configfile'))
  File "/root/eMonitor/emonitor/app.py", line 82, in create_app
    configure_extensions(app)
  File "/root/eMonitor/emonitor/app.py", line 165, in configure_extensions
    monitorserver.init_app(app)
  File "/root/eMonitor/emonitor/monitorserver.py", line 46, in init_app
    ip = socket.gethostbyname(socket.gethostname())
socket.gaierror: [Errno -2] Name or service not known

VG
Thomas

**Comment by seiferta** [comment]
mit python Version 2.7.13 habe ich es noch nicht getestet. Aber die Meldung besagt, dass die IP-Adresse nicht korrekt wäre oder nicht gefunden wurde.
Schnelle Hilfe:
in der Datei _emonitor/monitorserver.py_ in Zeile 46 die IP-Adresse manuell angeben.
z.B.
ip = "192.168.1.100"

In welcher Umgebung wurde eMonitor installiert? Ist ein Netzwerk konfiguriert?

**Comment by jonny1213** [comment]
Hallo Arne,

ja das hat geholfen.

Läuft auf einem KVM-Virt-Maschine unter Ubuntu 16.04. Netzwerk läuft.



Des Weiteren ist das Archiv mit dem Vbox-Image korrupt. Beim Öffnen kommt ein Fehler.





Viele Grüße
Thomas

--------------------------------
Thomas Schneider, Brunnenstr 62a, 86938 Schondorf, +49 8192 934365, +49 173 6506667



-----Ursprüngliche Nachricht-----
Von: Arne Seifert <notifications@github.com>
Gesendet: Die 4 Juli 2017 20:55
An: seiferta/eMonitor <eMonitor@noreply.github.com>
CC: Thomas Schneider <ts@flying-winnis.net>; Author <author@noreply.github.com>
Betreff: Re: [seiferta/eMonitor] flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead (#71)

mit python Version 2.7.13 habe ich es noch nicht getestet. Aber die Meldung besagt, dass die IP-Adresse nicht korrekt wäre oder nicht gefunden wurde.
 Schnelle Hilfe:
 in der Datei emonitor/monitorserver.py in Zeile 46 die IP-Adresse manuell angeben.
 z.B.
 ip = "192.168.1.100"

In welcher Umgebung wurde eMonitor installiert? Ist ein Netzwerk konfiguriert?

**Comment by seiferta** [comment]
Was für eine Fehlermeldung kommt denn beim Öffnen?

**Comment by jonny1213** [comment]
Mit 7-zip geht es.

Danke





Mit freundlichen Grüßen
Thomas Schneider


--------------------------------
Thomas Schneider, Brunnenstr 62a, 86938 Schondorf, +49 8192 934365 o +49 173 6506667

-----Ursprüngliche Nachricht-----
Von: Arne Seifert <notifications@github.com>
Gesendet: Mit 12 Juli 2017 08:32
An: seiferta/eMonitor <eMonitor@noreply.github.com>
CC: Thomas Schneider <ts@flying-winnis.net>; Author <author@noreply.github.com>
Betreff: Re: [seiferta/eMonitor] flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead (#71)

Was für eine Fehlermeldung kommt denn beim Öffnen?

**Comment by jonny1213** [comment]
Hallo Arne,

wie ist denn der Benutzername/Passwort für das Vbox-Image zur Anmeldung an das Adminpanel? emonitor/emonitor geht nicht.








Viele Grüße
Thomas

--------------------------------
Thomas Schneider, Brunnenstr 62a, 86938 Schondorf, +49 8192 934365, +49 173 6506667



-----Ursprüngliche Nachricht-----
Von: Thomas Schneider <ts@flying-winnis.net>
Gesendet: Mon 17 Juli 2017 10:44
An: seiferta/eMonitor <reply@reply.github.com>
Betreff: AW: [seiferta/eMonitor] flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead (#71)

Mit 7-zip geht es.

Danke





Mit freundlichen Grüßen
Thomas Schneider


--------------------------------
Thomas Schneider, Brunnenstr 62a, 86938 Schondorf, +49 8192 934365 o +49 173 6506667

-----Ursprüngliche Nachricht-----
Von: Arne Seifert <notifications@github.com>
Gesendet: Mit 12 Juli 2017 08:32
An: seiferta/eMonitor <eMonitor@noreply.github.com>
CC: Thomas Schneider <ts@flying-winnis.net>; Author <author@noreply.github.com>
Betreff: Re: [seiferta/eMonitor] flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead (#71)

Was für eine Fehlermeldung kommt denn beim Öffnen?

**Comment by seiferta** [comment]
emonitor/emonitor sind Benutzername und Passwort für das Linux vom Image.

Für die Admin-Oberfläche von eMonitor sind es Administrator/Admin

**Comment by jonny1213** [comment]
Administrator/Admin klappt nicht





Mit freundlichen Grüßen
Thomas Schneider


--------------------------------
Thomas Schneider, Brunnenstr 62a, 86938 Schondorf, +49 8192 934365 o +49 173 6506667

-----Ursprüngliche Nachricht-----
Von: Arne Seifert <notifications@github.com>
Gesendet: Die 18 Juli 2017 15:21
An: seiferta/eMonitor <eMonitor@noreply.github.com>
CC: Thomas Schneider <ts@flying-winnis.net>; Author <author@noreply.github.com>
Betreff: Re: [seiferta/eMonitor] flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead (#71)

emonitor/emonitor sind Benutzername und Passwort für das Linux vom Image.

Für die Admin-Oberfläche von eMonitor sind es Administrator/Admin

**Comment by seiferta** [comment]
Adminstrator/admin

sorry, damit muss es klappen

**Comment by jonny1213** [comment]
das klappt jetzt,

aber den Client findet (läuft auf einem Raspi)er nicht.

Ping vom Pi zum Server geht.







Mit freundlichen Grüßen
Thomas Schneider


--------------------------------
Thomas Schneider, Brunnenstr 62a, 86938 Schondorf, +49 8192 934365 o +49 173 6506667

-----Ursprüngliche Nachricht-----
Von: Arne Seifert <notifications@github.com>
Gesendet: Die 18 Juli 2017 15:21
An: seiferta/eMonitor <eMonitor@noreply.github.com>
CC: Thomas Schneider <ts@flying-winnis.net>; Author <author@noreply.github.com>
Betreff: Re: [seiferta/eMonitor] flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead (#71)

emonitor/emonitor sind Benutzername und Passwort für das Linux vom Image.

Für die Admin-Oberfläche von eMonitor sind es Administrator/Admin
