### ISSUE TITLE
Speicherproblem

### ISSUE THREAD

**Issue by mentor2002** [seiferta/eMonitor#72]
Sehr geehrter Herr Seifert,

für unser kleines  Gerätehaus waren wir auf der Suche nach einem Alarmdisplay, dabei sind wir auf ihr "emonitor" gestoßen. Hier haben wir uns die fertige VM heruntergeladen und auf einem Windows Server 2008R2 mittels VirtualBox entsprechend eingebunden. Das Programm ist, wie beschrieben, über den Port 8080 aus dem Windows Host herraus erreichbar, die Anmeldung als Admin zur Konfiguration unseres Standortes klappt auch.

Allerdings haben wir bei der Konfiguration Probleme. Bei jeglicher Änderung, z.B. des Standortes wirft der Browser die Fehlermeldung 500 und zeigt in der Virtualbox ein Speicherproblem an.
Fehlermeldung: No Space left on device (Siehe Bild_1) Unserem System steht jedoch genügend Speicherplatz (15 GB) zur Verfügung.

Können Sie uns bei der Fehlerbehebung helfen?

Mit freundlichen Grüßen,

FF Taucha
[Bild_1.pdf](https://github.com/seiferta/eMonitor/files/1245027/Bild_1.pdf)

**Comment by mentor2002** [comment]
wir haben es noch mal versucht weiter einzugrenzen... eventuell geben die erstellten Partitionen auf der fertigen *.vdi nicht genügend Platz her... kann es daren liegen?

Über eine Kontaktaufnahme wären wir sehr dankbar

FF Taucha

**Comment by seiferta** [comment]
Hallo,
die Partition ist mit der minimalen Größe erstellt, dass das Image nicht riesig wird.
Man kann diese Partition nachträglich vergrößern. Virtual-Box hat da ein entsprechendes Tool parat. Eine Google-Suche liefert da z.B. ein paar sinnvolle Treffer.

`C:\Programme\Oracle\VirtualBox\VBoxManage.exe" modifyhd "C:\[Pfad zum Volume].vdi" --resize 51200`

die Zahl ist dabei die Größe der Partition in MB.

Hoffe das hilft weiter

**Comment by mentor2002** [comment]
Hallo,

danke für die Antwort... das konkret hat leider so nicht funktioniert, hat uns aber auf den richtigen Weg gebracht. Mit einem Tool, welches ein Clone des Images erzeugt hat und dabei automatisch die Größe der Partition angepasst hat, war die Lösung des Problems.
Wir arbeiten weiter an der Installation des Emonitors für uns und es wäre schön, wenn wir hier in Kontakt bleiben könnten (ich würde ja hier auch Klarnamen und Email - Adresse hinterlegen, bin mir aber nicht so sicher, ob das dann nicht in falsche Hände gerät).

P.S. wir werden natürlich nicht bei jeder Kleinigkeit ankommen.

MfG LS

**Comment by seiferta** [comment]
sonst einfach über die Seite meiner Feuerwehr über das Webformular Kontakt aufnehmen http://www.ff-haar.de/technik/emonitor

Das geht dann direkt an mich.
