### ISSUE TITLE
Angeschlossene Bildschirme/Clients - kein Client angeschlossen

### ISSUE THREAD

**Issue by jonny1213** [seiferta/eMonitor#73]
Hallo,
auf einem Ubuntu 16.04 läuft der Server.
Zum Test zwei clients, einer auf einem Win 10 und einer auf einem PI.
Monitore sind auf dem Server angelegt und clients laufen.
Auf dem Server:
DEBUG:emonitor.signals:send signal monitorserver.clientsearchdone with: {'clients': ['1', '2']}
INFO:emonitor.signals:send signal monitorserver.clientsearchdone
DEBUG:emonitor.signals:send signal monitorserver.clientsearchstart with: {'clients': []}
INFO:emonitor.signals:send signal monitorserver.clientsearchstart
DEBUG:emonitor.signals:send signal monitorserver.clientsearchdone with: {'clients': ['1', '2']}
INFO:emonitor.signals:send signal monitorserver.clientsearchdone

Und auf den Clients jeweils:

addr ('192.168.22.112', 35014)
addr ('192.168.22.112', 59102)

die 112 ist der Server. 
Also finden scheinen sie sich.
Wenn ich unter Monitorkonfiguration/Monitore schaue wird aber angezeigt: "kein Client angeschlossen".
Die Clients bleiben auch schwarz.

Was mach ich falsch?

Danke
Gruß
Thomas

**Comment by seiferta** [comment]
Habe auch den Effekt, dass in der Anzeige "keine Clients angeschlossen" gezeigt wird, aber dennoch eine Anzeige auf den Clients ankommt.
Da hat sich anscheinend in einer der Python-Libs mal was geändert, dass das nicht mehr sauber klappt. Die Funktion ist aber dadurch nicht eingeschränkt.

Für genau diese Testfälle ist im Frontend unten rechts das kleine Icon mit dem Bildschirm gedacht, hierüber kann man an die Clients ein Testbild schicken, das dann auf dem Client angezeigt wird, falls alles korrekt konfiguriert ist.
Es kann sonst auch sein, dass die Clients und vor allem die Ansichten des Clients nicht korrekt im eMonitor angelegt sind.
Bitte mal ausprobieren und ggf. nochmal melden.

**Comment by jonny1213** [comment]
Hallo, das Testbild verschicken klappt nicht. Habe es auch mit dem V-Box-Image probiert. Der Client stellt zwar fest, dass der Server existiert aber weiter kommen sie nicht zusammen.
Hier der Log des Clients:
DEBUG:root:192.168.22.41:57326 - 2017.09.27 - 12:03:10: --> 0|reset|http://127.0.1.1:8080/monitor/{}
DEBUG:root:4.8.6
DEBUG:root:RESET
DEBUG:root:4.8.6
DEBUG:root:192.168.22.41:48048 - 2017.09.27 - 12:04:30: --> 0|ping
DEBUG:root:PING
DEBUG:root:192.168.22.41:42091 - 2017.09.27 - 12:04:36: --> 1|load|http://127.0.1.1:8080/monitor
DEBUG:root:4.8.6
DEBUG:root:LOAD: http://127.0.1.1:8080/monitor
DEBUG:root:192.168.22.41:55930 - 2017.09.27 - 12:04:40: --> 0|ping
DEBUG:root:PING
DEBUG:root:192.168.22.41:45914 - 2017.09.27 - 12:04:50: --> 0|ping
DEBUG:root:PING
DEBUG:root:192.168.22.41:56099 - 2017.09.27 - 12:05:06: --> 2|load|http://127.0.1.1:8080/monitor/{}?layoutid=3
DEBUG:root:192.168.22.41:33217 - 2017.09.27 - 12:05:10: --> 0|ping
DEBUG:root:PING
DEBUG:root:192.168.22.41:60458 - 2017.09.27 - 12:05:12: --> 2|load|http://127.0.1.1:8080/monitor
DEBUG:root:192.168.22.41:49249 - 2017.09.27 - 12:05:20: --> 1|load|http://127.0.1.1:8080/monitor/{}?layoutid=1
DEBUG:root:4.8.6
DEBUG:root:LOAD: http://127.0.1.1:8080/monitor/{}?layoutid=1
DEBUG:root:close
DEBUG:root:mclient started
DEBUG:root:mclient v 0.4.1 for eMonitor started with id 1, waiting for events...
DEBUG:root:reload last source 127.0.1.1:8080
DEBUG:root:192.168.22.93:1600 - 2017.09.27 - 12:05:42: --> initneed
DEBUG:root:4.8.6
DEBUG:root:192.168.22.41:33312 - 2017.09.27 - 12:05:58: --> 1|load|http://127.0.1.1:8080/monitor
DEBUG:root:4.8.6
DEBUG:root:LOAD: http://127.0.1.1:8080/monitor
DEBUG:root:192.168.22.41:49089 - 2017.09.27 - 12:07:10: --> 0|ping
DEBUG:root:PING


Was komisch ist: |load|http://127.0.1.1:8080/monitor.
Versucht er auf der dummy den Server zu erreichen?

Danke
Gruß
Thomas

**Comment by seiferta** [comment]
die 127.0.0.1 ist sicherlich das Problem, warum keine Daten an den Clients ankommen.

in der emonitor.cfg kann man einen Parameter "HOST" mit der korrekten IP ergänzen. Nach einem Neustart sollte dann auch eine Anzeige auf den Clients kommen.

`HOST = '192.168.22.112'`

Wichtig ist noch, dass das Log-File der clients gelöscht wird, da sonst wieder die letzte bekannte IP versucht wird, die ja nicht funktionieren kann.

**Comment by jonny1213** [comment]
Hallo,
das mit dem 
HOST = '192....'
hat funktioniert.
Danke
