### ISSUE TITLE
Telegram Einstellung / Fehler

### ISSUE THREAD

**Issue by jonny1213** [seiferta/eMonitor#76]
Hallo,
versuche grad den Telegram-Bereich zum laufen zu bringen.
1. Wie muss der "Telegramkey" in der cfg. aussehen? Der Ganze Token oder nur die Zahl?
2. Wenn ich auf speichern gehe bekomme ich nur eine leere Seite, aber folgenden Fehler:
Jan  9 23:07:56 failover rc.local[949]:   File "/srv/emonitor/emonitor/modules/settings/__init__.py", line 77, in getAdminContent
Jan  9 23:07:56 failover rc.local[949]:     return getAdminContent(self, **params)
Jan  9 23:07:56 failover rc.local[949]:   File "/srv/emonitor/emonitor/modules/settings/content_admin.py", line 98, in getAdminContent
Jan  9 23:07:56 failover rc.local[949]:     vals['telegramkey'] = request.form.get('telegrambot').strip()
Jan  9 23:07:56 failover rc.local[949]: TypeError: 'str' object does not support item assignment

Was mach ich falsch?
Danke

**Comment by seiferta** [comment]
1) es muss der komplette Token verwendet werden z.B. 
TELEGRAMKEY = '162111055:AAHV1qSGInodRASdjeVWovusMtQp4NkCq_2A'

2) nachdem die Konfiguration korrekt eingetragen wurde, sollte auch das Speichern funktionieren. Zumindest konnte ich das Problem nicht nachstellen.

**Comment by jonny1213** [comment]
Okay, auch wenn ich das mach funktioniert es nicht.
Der Key ist definitiv richtig, da wenn ich über die Konsole eine Nachricht verschicke es funktioniert.
1. im Admin Bereich steht "Telegram Bot nicht verfügbar: Entweder steht das Python-Modul nicht zur Verfügung oder der angegebene Bot-Schlüssel ist falsch:" in rot
2. 2018-01-11 11:09:52,635 - ERROR - emonitor.communication - error telegram
und nach wie vor obige Fehlermeldung.

**Comment by jonny1213** [comment]
Wer lesen kann ist klar im Vorteil: python-telegram-bot muss installiert werden.
Nun ist der installiert, dann kann man auch auf Speichern gehen.

Allerdings egal was ich mache:
"Telegram Bot nicht verfügbar: Entweder steht das Python-Modul nicht zur Verfügung oder der angegebene Bot-Schlüssel ist falsch:"

**Comment by jonny1213** [comment]
Okay, wenn man auf der Seite Messenger/Mail den Telegram-Key einträgt dann funktioniert es auch.
